// This file is to maintain all information on all cities in every map
// Note: GdpPerCapita, Disease, and Ethnicity should be values that are kept track of at the provincial level but will affect every city.

let map2Cities = [
  {
    "id": 0,
    "provinceID": 0,
    "planet": "Medera",
    "name": "Istanta",
    "isCapital": true,
    "cityPic": "public/images/city1.png",
    "xpos": 1625,
    "ypos": 2232,
    "baseDefense": 2,
    "owner": "Tehlike Empire",
    "ownerID": 0,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 11700000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['military-base', 'port'],
    "buildingHealth": ['150', '150']
  },
  {
    "id": 1,
    "provinceID": 1,
    "planet": "Medera",
    "name": "Borba",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1602,
    "ypos": 2222,
    "baseDefense": 1,
    "owner": "Tehlike Empire",
    "ownerID": 0,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 10800000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['port'],
    "buildingHealth": ['150']
  },
  {
    "id": 2,
    "provinceID": 0,
    "planet": "Medera",
    "name": "Loos",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1660,
    "ypos": 2180,
    "baseDefense": 2,
    "owner": "Tehlike Empire",
    "ownerID": 0,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 8700000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['port', 'military-base'],
    "buildingHealth": ['150', '150']
  },
  {
    "id": 3,
    "provinceID": 2,
    "planet": "Medera",
    "name": "Mudt",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1645,
    "ypos": 2096,
    "baseDefense": 0,
    "owner": "Tehlike Empire",
    "ownerID": 0,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 6600000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['port'],
    "buildingHealth": ['150']
  },
  {
    "id": 4,
    "provinceID": 2,
    "planet": "Medera",
    "name": "Tarat",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1678,
    "ypos": 1980,
    "baseDefense": 0,
    "owner": "Tehlike Empire",
    "ownerID": 0,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 5490000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": [],
    "buildingHealth": []
  },
  {
    "id": 5,
    "provinceID": 1,
    "planet": "Medera",
    "name": "Fustok",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1474,
    "ypos": 2138,
    "baseDefense": 0,
    "owner": "Tehlike Empire",
    "ownerID": 0,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 6690000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['port'],
    "buildingHealth": ['150']
  },
  {
    "id": 6,
    "provinceID": 3,
    "planet": "Medera",
    "name": "Geja",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1770,
    "ypos": 2070,
    "baseDefense": 0,
    "owner": "Tehlike Empire",
    "ownerID": 0,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 5250000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['power-plant-1'],
    "buildingHealth": ['120']
  },
  {
    "id": 7,
    "provinceID": 3,
    "planet": "Medera",
    "name": "Mejan",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1856,
    "ypos": 2066,
    "baseDefense": 0,
    "owner": "Tehlike Empire",
    "ownerID": 0,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 5850000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['port'],
    "buildingHealth": ['150']
  },
  {
    "id": 8,
    "provinceID": 0,
    "planet": "Medera",
    "name": "Tanara",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1800,
    "ypos": 2251,
    "baseDefense": 0,
    "owner": "Tehlike Empire",
    "ownerID": 0,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 6150000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['port'],
    "buildingHealth": ['150']
  },
  {
    "id": 9,
    "provinceID": 4,
    "planet": "Medera",
    "name": "Eqsa",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1910,
    "ypos": 2220,
    "baseDefense": 0,
    "owner": "Paneria",
    "ownerID": 1,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 5940000,
    "corporation": "Paneria",
    "corporationID": 1,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": [],
    "buildingHealth": []
  },
  {
    "id": 10,
    "provinceID": 4,
    "planet": "Medera",
    "name": "Manta",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1953,
    "ypos": 2291,
    "baseDefense": 0,
    "owner": "Paneria",
    "ownerID": 1,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 6360000,
    "corporation": "Paneria",
    "corporationID": 1,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['port'],
    "buildingHealth": ['150']
  },
  {
    "id": 11,
    "provinceID": 5,
    "planet": "Medera",
    "name": "Tun",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1870,
    "ypos": 2170,
    "baseDefense": 0,
    "owner": "Paneria",
    "ownerID": 1,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 7350000,
    "corporation": "Paneria",
    "corporationID": 1,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": [],
    "buildingHealth": []
  },
  {
    "id": 12,
    "provinceID": 5,
    "planet": "Medera",
    "name": "Sachanum",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 2006,
    "ypos": 2120,
    "baseDefense": 0,
    "owner": "Paneria",
    "ownerID": 1,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 10440000,
    "corporation": "Paneria",
    "corporationID": 1,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['port'],
    "buildingHealth": ['150']
  },
  {
    "id": 13,
    "provinceID": 6,
    "planet": "Medera",
    "name": "Pan",
    "isCapital": true,
    "cityPic": "public/images/city1.png",
    "xpos": 2090,
    "ypos": 2158,
    "baseDefense": 2,
    "owner": "Paneria",
    "ownerID": 1,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 13410000,
    "corporation": "Paneria",
    "corporationID": 1,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['port', 'military-base'],
    "buildingHealth": ['150', '150']
  },
  {
    "id": 14,
    "provinceID": 6,
    "planet": "Medera",
    "name": "Tera",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 2123,
    "ypos": 2180,
    "baseDefense": 2,
    "owner": "Paneria",
    "ownerID": 1,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 8550000,
    "corporation": "Paneria",
    "corporationID": 1,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['port', 'military-base'],
    "buildingHealth": ['150', '150']
  },
  {
    "id": 15,
    "provinceID": 6,
    "planet": "Medera",
    "name": "Sanum",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 2072,
    "ypos": 2298,
    "baseDefense": 0,
    "owner": "Paneria",
    "ownerID": 1,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 4350000,
    "corporation": "Paneria",
    "corporationID": 1,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['port'],
    "buildingHealth": ['150']
  },
  {
    "id": 16,
    "provinceID": 7,
    "planet": "Medera",
    "name": "Ejekt",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 2173,
    "ypos": 2159,
    "baseDefense": 1,
    "owner": "Paneria",
    "ownerID": 1,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 5580000,
    "corporation": "Paneria",
    "corporationID": 1,
    "corporateResourceModifier": 0.5,
    "building-slots": 2,
    "buildings": ['port'],
    "buildingHealth": ['150']
  },
  {
    "id": 17,
    "provinceID": 8,
    "planet": "Medera",
    "name": "Santet",
    "isCapital": true,
    "cityPic": "public/images/city1.png",
    "xpos": 1360,
    "ypos": 2187,
    "baseDefense": 1,
    "owner": "Veyra",
    "ownerID": 2,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 5670000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['port', 'military-base'],
    "buildingHealth": ['150', '150']
  },
  {
    "id": 18,
    "provinceID": 8,
    "planet": "Medera",
    "name": "Sahra",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1400,
    "ypos": 2220,
    "baseDefense": 1,
    "owner": "Veyra",
    "ownerID": 2,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 4260000,
    "corporation": "Tehlike",
    "corporationID": 0,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['military-base'],
    "buildingHealth": ['150']
  },
  {
    "id": 19,
    "provinceID": 9,
    "planet": "Medera",
    "name": "Sakuh",
    "isCapital": true,
    "cityPic": "public/images/city1.png",
    "xpos": 1459,
    "ypos": 2273,
    "baseDefense": 1,
    "owner": "Souhnd",
    "ownerID": 3,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": true,
    "population": 5160000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['port', 'military-base'],
    "buildingHealth": ['150', '150']
  },
  {
    "id": 20,
    "provinceID": 9,
    "planet": "Medera",
    "name": "Merda",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1400,
    "ypos": 2340,
    "baseDefense": 0,
    "owner": "Souhnd",
    "ownerID": 3,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 4410000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['power-plant-1'],
    "buildingHealth": ['120']
  },
  {
    "id": 21,
    "provinceID": 10,
    "planet": "Medera",
    "name": "Jake",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1300,
    "ypos": 2330,
    "baseDefense": 1,
    "owner": "Souhnd",
    "ownerID": 3,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 3690000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['military-base'],
    "buildingHealth": ['150']
  },
  {
    "id": 22,
    "provinceID": 10,
    "planet": "Medera",
    "name": "Fashin",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1350,
    "ypos": 2260,
    "baseDefense": 0,
    "owner": "Souhnd",
    "ownerID": 3,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 2880000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['power-plant-1'],
    "buildingHealth": ['120']
  },
  {
    "id": 23,
    "provinceID": 11,
    "planet": "Medera",
    "name": "Geshka",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1290,
    "ypos": 2390,
    "baseDefense": 0,
    "owner": "Tuetoro",
    "ownerID": 4,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 3420000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['power-plant-1'],
    "buildingHealth": ['120']
  },
  {
    "id": 24,
    "provinceID": 11,
    "planet": "Medera",
    "name": "Serba",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1350,
    "ypos": 2410,
    "baseDefense": 0,
    "owner": "Tuetoro",
    "ownerID": 4,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 4845000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['power-plant-1'],
    "buildingHealth": ['120']
  },
  {
    "id": 25,
    "provinceID": 12,
    "planet": "Medera",
    "name": "Ethny",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1470,
    "ypos": 2390,
    "baseDefense": 1,
    "owner": "Tuetoro",
    "ownerID": 4,
    "occupiedBy": "",
    "equatorial": true,
    "coastal": false,
    "population": 2745000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['military-base'],
    "buildingHealth": ['150']
  },
  {
    "id": 26,
    "provinceID": 12,
    "planet": "Medera",
    "name": "Fenter",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1350,
    "ypos": 2485,
    "baseDefense": 1,
    "owner": "Tuetoro",
    "ownerID": 4,
    "occupiedBy": "",
    "equatorial": false,
    "coastal": false,
    "population": 2739000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['military-base'],
    "buildingHealth": ['150']
  },
  {
    "id": 27,
    "provinceID": 12,
    "planet": "Medera",
    "name": "Castay",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1494,
    "ypos": 2462,
    "baseDefense": 1,
    "owner": "Tuetoro",
    "ownerID": 4,
    "occupiedBy": "",
    "equatorial": false,
    "coastal": true,
    "population": 5940000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['port', 'military-base'],
    "buildingHealth": ['150', '150']
  },
  {
    "id": 28,
    "provinceID": 13,
    "planet": "Medera",
    "name": "Bremun",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1500,
    "ypos": 2505,
    "baseDefense": 1,
    "owner": "Tuetoro",
    "ownerID": 4,
    "occupiedBy": "",
    "equatorial": false,
    "coastal": false,
    "population": 2970000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['military-base'],
    "buildingHealth": ['150']
  },
  {
    "id": 29,
    "provinceID": 13,
    "planet": "Medera",
    "name": "Magenta",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1555,
    "ypos": 2610,
    "baseDefense": 1,
    "owner": "Tuetoro",
    "ownerID": 4,
    "occupiedBy": "",
    "equatorial": false,
    "coastal": false,
    "population": 3972000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.25,
    "building-slots": 2,
    "buildings": ['military-base'],
    "buildingHealth": ['150']
  },
  {
    "id": 30,
    "provinceID": 14,
    "planet": "Medera",
    "name": "VenGuard",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1425,
    "ypos": 2530,
    "baseDefense": 1,
    "owner": "Tuetoro",
    "ownerID": 4,
    "occupiedBy": "",
    "equatorial": false,
    "coastal": false,
    "population": 6615000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['military-base'],
    "buildingHealth": ['150']
  },
  {
    "id": 31,
    "provinceID": 14,
    "planet": "Medera",
    "name": "Simfit",
    "isCapital": false,
    "cityPic": "public/images/city1.png",
    "xpos": 1468,
    "ypos": 2634,
    "baseDefense": 1,
    "owner": "Tuetoro",
    "ownerID": 4,
    "occupiedBy": "",
    "equatorial": false,
    "coastal": true,
    "population": 4215000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['military-base', 'power-plant-1'],
    "buildingHealth": ['150', '120']
  },
  {
    "id": 32,
    "provinceID": 14,
    "planet": "Medera",
    "name": "Mearl",
    "isCapital": true,
    "cityPic": "public/images/city1.png",
    "xpos": 1404,
    "ypos": 2604,
    "baseDefense": 2,
    "owner": "Tuetoro",
    "ownerID": 4,
    "occupiedBy": "",
    "equatorial": false,
    "coastal": true,
    "population": 8520000,
    "corporation": "Tuetoron",
    "corporationID": 2,
    "corporateResourceModifier": 0.165,
    "building-slots": 2,
    "buildings": ['military-base', 'port'],
    "buildingHealth": ['150', '150']
  },
]
